<?php

// autoload_static.php @generated by LockBadUserComposer

namespace LockBadUserComposer\Autoload;

class LockBadUserLockBadUserComposerStaticInit
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LockBadUser\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LockBadUser\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'LockBadUserComposer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = LockBadUserLockBadUserComposerStaticInit::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = LockBadUserLockBadUserComposerStaticInit::$prefixDirsPsr4;
            $loader->classMap = LockBadUserLockBadUserComposerStaticInit::$classMap;

        }, null, ClassLoader::class);
    }
}
