<?php

// autoload_psr4.php @generated by LockBadUserComposer

$autoloaderDir = dirname(dirname(__FILE__));
$baseDir = dirname($autoloaderDir);

return array(
    'LockBadUser\\' => array($baseDir . '/app'),
);
