<?php

// autoload_classmap.php @generated by LockBadUserComposer

$autoloaderDir = dirname(dirname(__FILE__));
$baseDir = dirname($autoloaderDir);

return array(
    'LockBadUserComposer\\InstalledVersions' => $autoloaderDir . '/composer/InstalledVersions.php',
);
